version: "3.4"
services:
 server:
   image: node:alpine
   container_name: server_dev_container
   entrypoint: /bin/sh
   ports:
     - 7000:7000
   working_dir: /srv/app
   volumes:
     - type: bind
       source: ./
       target: /srv/app
   tty: true
   command: entrypoint.sh

 db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

 adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
